language: java

sudo: required

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

install:
  - export MAVEN_HOME=/usr/local/maven-3.5.0

script:
  - mvn clean install
  - mvn package -DskipTests
  - cd dspot
  - java -jar target/dspot-1.0.1-jar-with-dependencies.jar --example

after_success:
  - mvn clean test jacoco:report coveralls:report
