name: DSpot - Diff-Test-Selection CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn install -DskipTests
      - name: Test with Maven
        run: cd dspot-diff-test-selection && mvn test -DdoIntegrationTests=true -Dorg.slf4j.simpleLogger.defaultLogLevel=error
