apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dspot
  name: dspot-web
  labels:
    app: dspot-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dspot-web
  template:
    metadata:
      labels:
        app: dspot-web
    spec:
      containers:
      - name: dspot-web
        image: tailp/dspot-web
        ports:
          - containerPort: 3000
        env:
        - name: MONGODB_HOST
          value: mongodb://mongo.repairnator:27017 # default if service of Mongodb deployed on K8s is called mongo with port 27017.
        - name: ACTIVEMQ_HOSTNAME
          value: activemq.repairnator
---
apiVersion: v1
kind: Service
metadata:
  namespace: dspot
  name: dspot-web
spec:
  selector:
    app: dspot-web
  ports:
  - name: web
    port: 3000
    targetPort: 3000